from django.urls import path
from .views import (
    AzureStorageAccountsAPIView,
    AzureSubscriptionsAPIView,
    AzureResourceGroupsAPIView,
    AzureRegionsAPIView,
    AzureCreateVNetAPIView,
    AzureCreateVMAPIView,
    AzureCreateResourceGroupAPIView,
    AzureCreateKeyVaultAPIView,
    AzureCreateBackupAPIView,
    AzureCreateServicePrincipalAPIView,
    AzureVerifiedDomainsAPIView,
    AzureCreateUserAPIView,
    AzureCreateGroupAPIView,
    AzureADUsersCountAPIView,
    AzureADUsersListAPIView,
    AzureLookupServicePrincipalByIdAPIView,
    AzureAssignServicePrincipalRoleAPIView,
    AzureVNetListAPIView,
    AzureNSGAPIView,
    AssignRole1APIView,
    AzureViewRolesAPIView,
    AzureDeleteRoleAPIView,
    AzureDebugConfigAPIView,
    get_in_use_service_principals,
    get_logs_by_request,
    get_payload_by_request,
    get_service_principals,
    delete_service_principal,
    DeleteUserAPIView,
    assign_role_to_principal as legacy_assign_role_function,
    create_keyvault_with_pe,
    list_resources,
    list_subnets,
    delete_resource_group,
    delete_resource,
    detach_public_ip,
)

urlpatterns = [
    path("storage-accounts/", AzureStorageAccountsAPIView.as_view()),
    path("subscriptions/", AzureSubscriptionsAPIView.as_view()),
    path("debug-config/", AzureDebugConfigAPIView.as_view()),
    path("resource-groups/", AzureResourceGroupsAPIView.as_view()),
    path("regions/", AzureRegionsAPIView.as_view()),
    path("create-resource-group/", AzureCreateResourceGroupAPIView.as_view()),
    path("create-vnet/", AzureCreateVNetAPIView.as_view()),
    path("create-vm/", AzureCreateVMAPIView.as_view()),
    path("create-key-vault/", AzureCreateKeyVaultAPIView.as_view()),
    path("create-backup/", AzureCreateBackupAPIView.as_view()),
    path("create-service-principal/", AzureCreateServicePrincipalAPIView.as_view()),
    path("verified-domains/", AzureVerifiedDomainsAPIView.as_view()),
    path("create-user/", AzureCreateUserAPIView.as_view()),
    path("create-group/", AzureCreateGroupAPIView.as_view()),
    path("ad-users/", AzureADUsersListAPIView.as_view()),
    path("ad-users-count/", AzureADUsersCountAPIView.as_view()),
    path("assign-role/", AzureAssignServicePrincipalRoleAPIView.as_view()),
    path(
        "assign-role-legacy/<int:resource_id>/<str:role_name>/",
        legacy_assign_role_function,
        name="assign_role_legacy",
    ),
    path("lookup-service-principal/", AzureLookupServicePrincipalByIdAPIView.as_view()),
    path("vnets/", AzureVNetListAPIView.as_view()),
    path("nsg/", AzureNSGAPIView.as_view()),
    path("subnets/", list_subnets),
    path("create-keyvault-with-pe/", create_keyvault_with_pe),
    path("resources/", list_resources),
    path("delete-resource-group/", delete_resource_group),
    path("delete-resource/", delete_resource),
    path("detach-public-ip/", detach_public_ip),
    path("react/assign-role/", AssignRole1APIView.as_view(), name="assign-role"),
    path("view-roles/", AzureViewRolesAPIView.as_view(), name="view-roles"),
    path("delete-role/", AzureDeleteRoleAPIView.as_view(), name="delete-role"),
    path("service-principals/in-use/", get_in_use_service_principals, name="get-in-use-service-principals"),
    path("service-principals/", get_service_principals, name="get-service-principals"),
    path("service-principals/<str:sp_id>/delete/", delete_service_principal, name="delete-service-principal"),
    path("logs/<str:request_id>/", get_logs_by_request),
    path("payload/<str:request_id>/", get_payload_by_request),
    path("delete-user/<str:user_id>/", DeleteUserAPIView.as_view(), name="delete-user"),
]
