# Generated by Django 6.0.2 on 2026-04-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moniter', '0002_managedserviceprincipal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apilog',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='apilog',
            name='generated_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
