# Generated by Django 6.0.2 on 2026-04-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moniter', '0003_rename_timestamp_apilog_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestPayload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=100, unique=True)),
                ('process_name', models.CharField(max_length=100)),
                ('input_payload', models.JSONField(blank=True, null=True)),
                ('output_payload', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
