import React, { useEffect, useState } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import "./DashboardStatus.css";
import { API_BASE_URL, readBackendJson } from "./api/apiHelpers";

const Dashboard = ({
  requestId: propRequestId,
  inputPayload: propInputPayload,
  processName: propProcessName,
}) => {
  const location = useLocation();
  const navigate = useNavigate();

  const state = location.state || {};
  const resolvedRequestId = propRequestId || state.requestId;
  const resolvedProcessName = propProcessName || state.processName || "User operation";
  const resolvedStatus = state.status || "running";
  const resolvedInputPayload = propInputPayload || state.inputPayload || null;

  if (!resolvedRequestId) {
    return (
      <div className="mt-8">
        <h2 className="text-2xl font-bold mb-3">Dashboard</h2>
        <p className="text-lg mb-3">
          No active process. Start a user creation to see its progress.
        </p>
        <button
          type="button"
          className="user-back"
          onClick={() => navigate("/create-user")}
        >
          {"<- Create User"}
        </button>
      </div>
    );
  }
  const [logs, setLogs] = useState([]);
  const [outputPayload, setOutputPayload] = useState(null);
  const [completed, setCompleted] = useState(false);
  const [loading, setLoading] = useState(false);

  // 🔁 Poll Logs
  useEffect(() => {
    if (!resolvedRequestId) return;

    const interval = setInterval(async () => {
      try {
        const response = await fetch(
          `${API_BASE_URL}/api/monitor/azure/logs/${resolvedRequestId}/`
        );

        const data = await readBackendJson(response);

        if (response.ok) {
          setLogs(data);

          const allSuccess =
            data.length > 0 &&
            data.every((log) => log.status.toLowerCase() === "success");

          if (allSuccess) {
            setCompleted(true);
            clearInterval(interval);
          }
        }
      } catch (err) {
        console.error(err);
      }
    }, 3000);

    return () => clearInterval(interval);
  }, [resolvedRequestId]);

  // 🔹 Fetch OUTPUT payload after completion
  useEffect(() => {
    if (!completed || !resolvedRequestId) return;

    const fetchOutputPayload = async () => {
      setLoading(true);

      try {
        const response = await fetch(
          `${API_BASE_URL}/api/monitor/azure/payload/${resolvedRequestId}/`
        );

        const data = await readBackendJson(response);

        if (response.ok) {
          setOutputPayload(data.payload);
        }
      } catch (err) {
        console.error(err);
      } finally {
        setLoading(false);
      }
    };

    fetchOutputPayload();
  }, [completed, resolvedRequestId]);

  // 🔥 Mask function (works for BOTH payloads)
  const formatPayload = (data) => {
    if (!data) return "";

    const formatted = { ...data };

    if (formatted.password) {
      formatted.password = "••••••••";
    }

    if (formatted.autoGeneratedPassword) {
      formatted.password = "Auto Generated";
    }

    return JSON.stringify(formatted, null, 2);
  };

  const getStatus = (status) => {
    if (status === "success") return "Success";
    if (status === "accepted") return "Accepted";
    if (status === "failed") return "Failed";
    if (status === "running") return "Running";
    return "Pending";
  };

  return (
    <div className="mt-8">
      <div>
        <button onClick={() => navigate("/")}>
          {" <- Back"}
        </button>
      </div>
      {/* 🔷 Title */}
      <h2 className="text-2xl font-bold mb-3">Dashboard</h2>

      {/* 🔷 Start Message */}
      <div className="mb-4 text-lg">
        {resolvedProcessName
          ? `Your ${resolvedProcessName} process has started`
          : "Your process has started"}
      </div>
      <div className="mb-2 text-sm text-gray-600">
        Status: {getStatus(resolvedStatus)}
      </div>

      {/* 🔷 INPUT PAYLOAD (Immediate) */}
      <div className="mb-6">
        <h3 className="font-semibold mb-2">
          Payload (What you submitted)
        </h3>
        <pre className="bg-gray-100 p-3 rounded text-sm overflow-x-auto">
          {formatPayload(resolvedInputPayload)}
        </pre>
      </div>

      {/* 🔷 TABLE (Steps) */}
      <div className="overflow-x-auto rounded border border-gray-300 bg-white shadow-sm">
        <table className="min-w-full divide-y divide-gray-200 dashboard-table">
          <thead className="bg-gray-50 text-xs uppercase text-gray-500">
            <tr>
              <th className="px-3 py-2">UUID</th>
              <th className="px-3 py-2">Step Name</th>
              <th className="px-3 py-2">Status</th>
              <th className="px-3 py-2">Logs</th>
            </tr>
          </thead>
          <tbody>
            {logs.length === 0 ? (
              <tr>
                <td colSpan="4" className="text-center py-4">
                  Waiting for logs...
                </td>
              </tr>
            ) : (
              logs.map((log, index) => (
                <tr key={index}>
                  <td className="px-3 py-2 font-mono">{resolvedRequestId}</td>
                  <td className="px-3 py-2">{log.step_name}</td>
                  <td className="px-3 py-2">{getStatus(log.status)}</td>
                  <td className="px-3 py-2">{log.message}</td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>

      {/* 🔷 OUTPUT PAYLOAD (After completion) */}
      {completed && (
        <div className="mt-6">
          <h3 className="font-semibold mb-2">
            Payload (Generated by system)
          </h3>

          {loading ? (
            <p>Loading output payload...</p>
          ) : (
            <pre className="bg-gray-100 p-3 rounded text-sm overflow-x-auto">
              {formatPayload(outputPayload)}
            </pre>
          )}
        </div>
      )}

    </div>
  );
};

export default Dashboard;