# Generated by Django 6.0.2 on 2026-03-31 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moniter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedServicePrincipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_principal_id', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
